---
# allowerasing to true so vim replaces nano as default editor
- name: install packages
  dnf:
    name: "{{ my_packages }}"
    state: present
    allowerasing: true
  notify: yum-clean-metadata
  become: true

- name: Remove packages
  dnf:
    name: "{{ removed_packages }}"
    state: absent
  become: true

- name: Update latest
  dnf:
    name: "*"
    state: latest
  notify: yum-clean-metadata
  become: true
