---
- name: install Go programming language
  dnf:
    name: golang
    state: present
  become: true

- name: create directory for Go packages
  file:
    path: "{{ ansible_user_dir }}/go"
    state: directory
