---
# Spotify
- name: add fedora-spotify repo
  get_url:
    url: http://negativo17.org/repos/fedora-spotify.repo
    dest: /etc/yum.repos.d/fedora-spotify.repo
  become: true

- name: install Spotify
  dnf:
    name: spotify-client
    state: present
  become: true
