---
# Docker
- name: Install Docker
  dnf:
    name: docker
    state: present
  become: true

- name: create docker group
  group:
    name: docker
    state: present
  become: true

- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: stop docker
  service:
    name: docker
    state: stopped
  become: true

- name: remove any existing docker-storage config file
  file:
    path: /etc/sysconfig/docker-storage
    state: absent
  become: true

- name: create docker-storage-setup
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644
  become: True

- name: Run docker-storage-setup
  command: docker-storage-setup
  become: True

- name: start Docker daemon
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: add Red Hat docker registry
  lineinfile:
    dest: /etc/sysconfig/docker
    line: "ADD_REGISTRY='--add-registry registry.access.redhat.com'"
    insertafter: '^# ADD_REGISTRY='
    backup: yes
  become: true
  notify: restart docker
