---
# Bluejeans
- name: Get last bluejeans version
  shell: "curl -s https://www.bluejeans.com/downloads#desktop | grep -o -E 'href=\"([^\"#]+)\"'| cut -d'\"' -f2 | grep 'rpm$' | grep -vi bluejeans_events"
  register: bluejeansurl

- name: Install Bluejeans
  dnf:
    name: "{{ bluejeansurl.stdout }}"
    state: present
    disable_gpg_check: yes
  become: true
