---
# Bluejeans
- name: Get last bluejeans version
  shell: "curl -s https://support.bluejeans.com/knowledge/app-large-deployment | grep -o -E 'href=\"([^\"#]+)\"'| cut -d'\"' -f2 | grep rpm"
  register: bluejeansurl

- name: Install Bluejeans
  dnf:
    name: "{{ bluejeansurl.stdout }}"
    state: present
  become: true
