# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/bash/powerline.sh
fi

#minishift added by me
export PATH=$PATH:$HOME/bin
export MINISHIFT_USERNAME=alosadag

#kubectl krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

alias k='kubectl'
alias kg='kubectl get'
alias kgp='kubectl get pods'
alias k9s='podman run --rm -it -v $KUBECONFIG:/root/.kube/config:Z quay.io/derailed/k9s'
alias oc_scc='oc get pod -o "custom-columns=NAME:metadata.name,APPLIED SCC:metadata.annotations.openshift\.io/scc"'
alias oc_get_alerts='curl -k -H "Authorization: Bearer $(oc -n openshift-monitoring sa get-token prometheus-k8s)"  https://$(oc -n openshift-monitoring get routes -o "custom-columns=HTTP:spec.host" --no-headers | grep alertmanager)/api/v2/alerts | jq'

